// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.3
// source: helloworld/hello_world.proto

package helloworld

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskEvent_TaskOp int32

const (
	TaskEvent_UNKNOWN TaskEvent_TaskOp = 0
	TaskEvent_STATUS  TaskEvent_TaskOp = 1
)

// Enum value maps for TaskEvent_TaskOp.
var (
	TaskEvent_TaskOp_name = map[int32]string{
		0: "UNKNOWN",
		1: "STATUS",
	}
	TaskEvent_TaskOp_value = map[string]int32{
		"UNKNOWN": 0,
		"STATUS":  1,
	}
)

func (x TaskEvent_TaskOp) Enum() *TaskEvent_TaskOp {
	p := new(TaskEvent_TaskOp)
	*p = x
	return p
}

func (x TaskEvent_TaskOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEvent_TaskOp) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_hello_world_proto_enumTypes[0].Descriptor()
}

func (TaskEvent_TaskOp) Type() protoreflect.EnumType {
	return &file_helloworld_hello_world_proto_enumTypes[0]
}

func (x TaskEvent_TaskOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEvent_TaskOp.Descriptor instead.
func (TaskEvent_TaskOp) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_hello_world_proto_rawDescGZIP(), []int{2, 0}
}

type TaskEventResponse_TaskStatus int32

const (
	TaskEventResponse_UNKNOWN  TaskEventResponse_TaskStatus = 0
	TaskEventResponse_WAITING  TaskEventResponse_TaskStatus = 1
	TaskEventResponse_SATRTED  TaskEventResponse_TaskStatus = 2
	TaskEventResponse_FNISHEDI TaskEventResponse_TaskStatus = 3
)

// Enum value maps for TaskEventResponse_TaskStatus.
var (
	TaskEventResponse_TaskStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "WAITING",
		2: "SATRTED",
		3: "FNISHEDI",
	}
	TaskEventResponse_TaskStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"WAITING":  1,
		"SATRTED":  2,
		"FNISHEDI": 3,
	}
)

func (x TaskEventResponse_TaskStatus) Enum() *TaskEventResponse_TaskStatus {
	p := new(TaskEventResponse_TaskStatus)
	*p = x
	return p
}

func (x TaskEventResponse_TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEventResponse_TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_hello_world_proto_enumTypes[1].Descriptor()
}

func (TaskEventResponse_TaskStatus) Type() protoreflect.EnumType {
	return &file_helloworld_hello_world_proto_enumTypes[1]
}

func (x TaskEventResponse_TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEventResponse_TaskStatus.Descriptor instead.
func (TaskEventResponse_TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_hello_world_proto_rawDescGZIP(), []int{3, 0}
}

// The request message containing the user's name
type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_hello_world_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_hello_world_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_hello_world_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_hello_world_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_hello_world_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_helloworld_hello_world_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string  `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TaskIds  []int64 `protobuf:"varint,2,rep,packed,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	Op       string  `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_hello_world_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_hello_world_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_helloworld_hello_world_proto_rawDescGZIP(), []int{2}
}

func (x *TaskEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TaskEvent) GetTaskIds() []int64 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *TaskEvent) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

type TaskEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId int64                        `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status TaskEventResponse_TaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=helloworld.TaskEventResponse_TaskStatus" json:"status,omitempty"`
}

func (x *TaskEventResponse) Reset() {
	*x = TaskEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_hello_world_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEventResponse) ProtoMessage() {}

func (x *TaskEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_hello_world_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEventResponse.ProtoReflect.Descriptor instead.
func (*TaskEventResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_hello_world_proto_rawDescGZIP(), []int{3}
}

func (x *TaskEventResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskEventResponse) GetStatus() TaskEventResponse_TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskEventResponse_UNKNOWN
}

var File_helloworld_hello_world_proto protoreflect.FileDescriptor

var file_helloworld_hello_world_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0a,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x76, 0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x21, 0x0a, 0x06, 0x54, 0x61, 0x73,
	0x6b, 0x4f, 0x70, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x01, 0x22, 0xb1, 0x01, 0x0a,
	0x11, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x40, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x41, 0x0a,
	0x0a, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x49, 0x54,
	0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x41, 0x54, 0x52, 0x54, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x49, 0x10, 0x03,
	0x32, 0x64, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x59, 0x0a, 0x08, 0x53,
	0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x15, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65,
	0x63, 0x68, 0x6f, 0x3a, 0x01, 0x2a, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_helloworld_hello_world_proto_rawDescOnce sync.Once
	file_helloworld_hello_world_proto_rawDescData = file_helloworld_hello_world_proto_rawDesc
)

func file_helloworld_hello_world_proto_rawDescGZIP() []byte {
	file_helloworld_hello_world_proto_rawDescOnce.Do(func() {
		file_helloworld_hello_world_proto_rawDescData = protoimpl.X.CompressGZIP(file_helloworld_hello_world_proto_rawDescData)
	})
	return file_helloworld_hello_world_proto_rawDescData
}

var file_helloworld_hello_world_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_helloworld_hello_world_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_helloworld_hello_world_proto_goTypes = []interface{}{
	(TaskEvent_TaskOp)(0),             // 0: helloworld.TaskEvent.TaskOp
	(TaskEventResponse_TaskStatus)(0), // 1: helloworld.TaskEventResponse.TaskStatus
	(*HelloRequest)(nil),              // 2: helloworld.HelloRequest
	(*HelloReply)(nil),                // 3: helloworld.HelloReply
	(*TaskEvent)(nil),                 // 4: helloworld.TaskEvent
	(*TaskEventResponse)(nil),         // 5: helloworld.TaskEventResponse
}
var file_helloworld_hello_world_proto_depIdxs = []int32{
	1, // 0: helloworld.TaskEventResponse.status:type_name -> helloworld.TaskEventResponse.TaskStatus
	2, // 1: helloworld.Greeter.SayHello:input_type -> helloworld.HelloRequest
	3, // 2: helloworld.Greeter.SayHello:output_type -> helloworld.HelloReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_helloworld_hello_world_proto_init() }
func file_helloworld_hello_world_proto_init() {
	if File_helloworld_hello_world_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_helloworld_hello_world_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_hello_world_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_hello_world_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_hello_world_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_helloworld_hello_world_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_hello_world_proto_goTypes,
		DependencyIndexes: file_helloworld_hello_world_proto_depIdxs,
		EnumInfos:         file_helloworld_hello_world_proto_enumTypes,
		MessageInfos:      file_helloworld_hello_world_proto_msgTypes,
	}.Build()
	File_helloworld_hello_world_proto = out.File
	file_helloworld_hello_world_proto_rawDesc = nil
	file_helloworld_hello_world_proto_goTypes = nil
	file_helloworld_hello_world_proto_depIdxs = nil
}
